Sphere stars generation
lycantropos/alcor pull request #17
Opened 2017-08-27 14:43 UTC by LostFan123

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   halo_age: float = 14.,
зачем запятая в конце? перенос на следующую строку тоже можно убрать, без проблем влезет

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def generate_stars(max_stars_count: int = 6E6,
`6E6` не `int`, а `float`, так что лучше сделать
```python
max_stars_count: int = 6_000_000
```

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   time_bins_count: int = 5000,
аналогично, мы можем (начиная с версии `Python 3.6`) улучшить внешний вид с помощью underscore в числовых литералах
```python
time_bins_count: int = 5_000
```
если же нужно будет интерполировать строку и добавить underscore, то можно указать с помощью опции `_` (опции передаются после `:`)
```python
>>> '{:_}'.format(10 ** 9)
'1_000_000_000'
>>> '1 billion can be represented as {billion:_}'.format(billion=10 ** 9)
'1 billion can be represented as 1_000_000_000'
```

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                sys.exit()
нужно `raise`'ить exception само собой, никогда не используй `sys.exit`

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                sys.exit()
тогда и логгировать ошибку незачем, сообщение в теле exception'а слать и всё

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +            if random() <= thick_disk_stars_fraction:
это ужасный spaghetti-код, я уже говорил много раз, что если нет блока else, то следует вместо
```python
if condition:
    ...
```
писать
```python
if not condition:
    continue
...
```

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +            if random() <= thick_disk_stars_fraction:
в данном случае часть `...` крайне объёмна, стоит вынести в отдельную функцию

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +            if galactic_structure_types[-1] == GalacticStructureType.thin:
зачем многократно доставать `galactic_structure_types[-1]`? нужно дать этому объекту говорящее имя

2017-10-11 14:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                # TODO: change this
`change this` на что? такие комментарии хуже всего, понятны только автору в момент написания, а через неделю уже никто не будет знать, что имелось ввиду

2017-10-12 13:11 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +            if random() <= thick_disk_stars_fraction:
yо у нас же есть блок else

2017-10-12 14:00 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +            if random() <= thick_disk_stars_fraction:
или ты про другое место. так писал бы там коммент.

2017-10-23 17:28 UTC, lycantropos requested changes

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                  log)
давай договоримся импортировать `math` просто и вытаскивать его составляющие как атрибуты

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def normalization_const(star_formation_rate_param: float,
keyword-only

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        initial_mass_function_param: float,
аналогично

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        ) -> float:
перенос избыточен

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def get_mass_from_salpeter_initial_mass_function(
почему так длинно? если сделать `salpeter_initial_mass_function`?

2017-10-23 17:28 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        time_try_sfr = (time_try
что за аббревиатуры?

2017-10-23 18:07 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    birth_times = []
вижу что заполняем, не могу понять как используется

2017-10-23 18:18 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   max_stars_count: int = 6_000_000,
эта строка и нижняя зафейлятся для `Python 3.5`

2017-10-23 18:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +# https://www.google.es/search?q=star+formation+rate
мб в докстринг лучше оформить, а не вне функции?

2017-10-23 18:21 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                    halo_stars_fraction=halo_stars_fraction)
это же вне цикла вычислимо, разве нет?

2017-10-23 18:23 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                raise Exception('Number of stars is too high - '
кидать сырой `Exception` плохо, можно использовать `ValueError` или [`OverflowError`](https://docs.python.org/3.6/library/exceptions.html#OverflowError)

2017-10-23 18:23 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                'decrease mass reduction factor')
точка в конце сообщений как правило повышает их читаемость

2017-10-23 18:29 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                    halo_stars_fraction=halo_stars_fraction)
не думаю, что это хорошая идея. там внутри RNG если что

2017-10-26 02:26 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                        star_formation_rate_param: float,
почему `param`, а не `coef` или к чему сокращать -- `coefficient`?

2017-10-26 02:26 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    """Return birth time of a thick disk star by using Monte Carlo method.
по-моему многострочный докстринг читаемей выглядит когда начинается со следующей строки
```python
"""
...
"""
```
так начало и конец выглядят более консистентно

2017-10-26 19:16 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                        star_formation_rate_param: float,
коэффициент - это же множитель, разве нет?

2017-10-26 19:19 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    """Return birth time of a thick disk star by using Monte Carlo method.
ок. я просто следовал примеру в каком-то PEP

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                   + time_increment * random())
стоит по аналогии с `thick_disk_star_birth_time ` вынести эти вычисления во вспомогательные функции `halo_disk_star_birth_time` & `thin_disk_star_birth_time`

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                   + halo_stars_formation_time * random())
почему здесь не меняется `scale_height`?

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                scale_height = thin_disk_scale_height_kpc
что мешает вынести эту логику в `if` ниже? потому что насколько я могу судить `scale_height` нужен именно там, тогда и стоит определять его в том месте

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                total_bin_mass += star_mass
это тоже можно вынести в отдельный `if`

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   halo_age: float = 14.
если поместить схожие параметры рядом, то читаемость улучшится

2017-10-27 02:47 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   halo_age: float = 14.
вроде `thin_disk_age`, `thick_disk_age`, `halo_age` (они же связаны?)

2017-10-27 13:23 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                                   + halo_stars_formation_time * random())
у halo stars распределение координат другое (cферическое) и там свои параметры. 
в этом модуле на данном этапе вычислений невозможно для halo генерировать все координаты вроде как.
вообще не думаю, что это правильно, в этом модуле присваивать координату z для thin и thick disk stars
странно, кому вообще только могла прийти идея её здесь считать, отдельно от остальных координат

2017-10-27 13:41 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                scale_height = thin_disk_scale_height_kpc
удалил генерацию z-координаты. функцию внизу оставил. потом перенесу в другой модуль

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +# TODO: take these consts to settings file
верно, стоит подумать над их расположением и именами, так как их уже много, можно в отдельную директорию их примеры поместить и добавить README по тому, что из себя представляет каждый параметр и на что он влияет (это непросто, но оно явно того стоит)

но для начала можно оставить и так, главное -- получить рабочую версию

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        y_imf = mass ** parameter
что такое `imf`?

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def initial_star_mass_by_salpeter(parameter: float,
где в функции фигурирует `salpeter`?

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        time_try_sfr = time_try * math.exp(-time_try / thick_disk_sfr_param)
что такое `try`?

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        time_try_sfr = time_try * math.exp(-time_try / thick_disk_sfr_param)
почему бы `sfr` не расшифровать как `formation_rate`?

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                               thick_disk_birth_init_time: float) -> float:
предлагаю убрать префикс `thick_`, из контекста (названия функции) понятно, с каким типом мы имеем дело

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                               thick_disk_birth_init_time: float) -> float:
да и `disk_` тоже можно опустить

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    Return birth time of a thick disk star by using Monte Carlo method.
вроде как договорились на `Returns`?

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    Return birth time of a thick disk star by using Monte Carlo method.
по-моему, можно опустить `by`

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                         halo_birth_init_time: float,
предлагаю не сокращать `init`, так как это не очевидно: *initial* или *initialized* или *initialization* или ещё что

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                         halo_birth_init_time: float,
аналогично, можно опустить префикс `halo_`

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
для чистоты предлагаю в подобных функциях сделать функцию `random` параметром типа `generator`, это поможет тестировать данные функции передавая какой-нибудь тривиальный генератор

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                thick_disk_stars_fraction: float,
если это некое соотношение и имеет значение от `0` до `1`, то такие объекты чаще называют `ratio`

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
объекты можно называть по аналогии с теми объектами, с которыми оно сравнивается (в данном случае `fraction` или `ratio`)

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
можно без префикса `random_`, особенно если мы поменяем интерфейс и будем работать с произвольным генератором

2017-12-07 09:13 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_sign = float(1. - 2. * int(2.0 * random()))
но ведь `sign` принимает значения `-1`, `1` (и иногда `0`)

2017-12-07 09:13 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +    return random() * (15. - halo_birth_init_time)
стоит написать стратегии

2017-12-07 11:03 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +        y_imf = mass ** parameter
initial mass function.
да тут вообще стоит подумать над именами переменных в этой функции.
по сути тут простой Монте-Карло
```python
    y_max = min_mass ** parameter

    mass_amplitude = max_mass - min_mass
    while True:
        y = y_max * random()
        mass = min_mass + mass_amplitude * random()
        y_imf = mass ** parameter
        if y <= y_imf:
            return mass
``` 
![drawing](https://user-images.githubusercontent.com/20144534/33711518-9e05111a-db44-11e7-9572-ef08f2df84d7.png)

Может, что-нибудь типа такого?
```python
    y_max = min_mass ** exponent

    while True:
        mass = random.uniform(min_mass, max_mass)
        y_mass = mass ** exponent
        if random.uniform(0, y_max) <= y_mass:
            return mass
```

2017-12-07 11:18 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +def initial_star_mass_by_salpeter(parameter: float,
[Salpeter (1955)](https://en.wikipedia.org/wiki/Initial_mass_function#Salpeter_(1955)) - это имя ученого, кто модель эту придумал. есть разные модели. надо как-то различать

2017-12-07 11:19 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +        time_try_sfr = time_try * math.exp(-time_try / thick_disk_sfr_param)
try/attempt/probe/trial/test. тут тоже Monte Carlo

2017-12-07 11:24 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                                thick_disk_stars_fraction: float,
забыл удалить эту функцию

2017-12-07 11:25 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                                thick_disk_stars_fraction: float,
и ratio - это же отношение, а мы про доли говорим, что и есть fractions

2017-12-07 11:29 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
удалил функцию. надобность в генераторе, я так понимаю, отпадает?

2017-12-07 11:31 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    random_sign = float(1. - 2. * int(2.0 * random()))
использовал `random.choice([-1, 1])`. пойдет?

2017-12-07 11:35 UTC, LostFan123 commented on tests/fixtures/sphere_stars.py
> +    return random() * (15. - halo_birth_init_time)
I'm on it

2017-12-07 16:50 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        y_imf = mass ** parameter
выглядит норм

2017-12-07 16:57 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
везде где есть вызов `random.random` советую сделать параметр со значением по умолчанию, это бесплатно, но делает код чище

2017-12-07 16:57 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    random_sign = float(1. - 2. * int(2.0 * random()))
выглядит лучше

2017-12-08 11:14 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +# TODO: take these consts to settings file
да

2017-12-08 11:15 UTC, LostFan123 commented on tests/fixtures/sphere_stars.py
> +    return random() * (15. - halo_birth_init_time)
написал

2017-12-08 11:15 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    random_sign = float(1. - 2. * int(2.0 * random()))
спасибо

2017-12-08 11:15 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    random_number = random()
сделано

2017-12-08 11:16 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                         halo_birth_init_time: float,
опустил

2017-12-08 11:19 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    Return birth time of a thick disk star by using Monte Carlo method.
сделано

2017-12-08 11:20 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                               thick_disk_birth_init_time: float) -> float:
опустил

2017-12-08 11:20 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +        y_imf = mass ** parameter
спасибо

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                formation_rate_parameter=thick_disk_sfr_param))
что мешает сделать 2 list comprehension'а?

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    thick_disk_stars['galactic_structure_type'] = GalacticStructureType.thick
почему нельзя добавить в `dict`?
```python
    return pd.DataFrame(dict(progenitor_mass=progenitors_masses,
                             birth_time=birth_times,
                             galactic_structure_type=GalacticStructureType.thick))
```

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    thick_disk_stars['galactic_structure_type'] = GalacticStructureType.thick
вообще мы можем возвращать `dict`, а в `DataFrame` оборачивать сверху?

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        uniform_rng: Callable[[float, float], float] = random.uniform
почему `rng`? что мешает передать любой генератор? зачем сужать область определения?

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                'decrease mass reduction factor.')
можно вынести этот фрагмент в отдельную функцию-генератор
```python
def give_me_a_proper_name(bin_initial_time: float,
                          birth_rate: float,
                          *,
                          max_stars_count: int,
                          time_increment: float,
                          initial_mass_function_parameter: float
                          ) -> Iterator[Tuple[float, float]]:
    total_bin_mass = 0.
    progenitors_count = 0
    while total_bin_mass < birth_rate:
        birth_time = thin_disk_star_birth_time(
            bin_initial_time=bin_initial_time,
            time_increment=time_increment)
        star_mass = initial_star_mass_by_salpeter(
            initial_mass_function_parameter)

        yield birth_time, star_mass

        total_bin_mass += star_mass
        progenitors_count += 1

        if progenitors_count > max_stars_count:
            raise OverflowError('Number of stars is too high - '
                                'decrease mass reduction factor.')
```

2017-12-08 17:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                'decrease mass reduction factor.')
мы можем пойти дальше и избавить сигнатуру этой функции от супа из параметров, если будем просто передавать генераторы для `birth_time` и `star_mass`
```python
def give_me_a_proper_name(birth_rate: float,
                          *,
                          max_stars_count: int,
                          birth_time_generator: Callable[[], float],
                          star_mass_generator: Callable[[], float]
                          ) -> Iterator[Tuple[float, float]]:
    total_bin_mass = 0.
    progenitors_count = 0
    while total_bin_mass < birth_rate:
        birth_time = birth_time_generator()
        star_mass = star_mass_generator()

        yield birth_time, star_mass

        total_bin_mass += star_mass
        progenitors_count += 1

        if progenitors_count > max_stars_count:
            raise OverflowError('Number of stars is too high - '
                                'decrease mass reduction factor.')
```

2017-12-08 20:31 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                formation_rate_parameter=thick_disk_sfr_param))
не красиво выглядело. но как хочешь. сделаю

2017-12-08 21:13 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    thick_disk_stars['galactic_structure_type'] = GalacticStructureType.thick
можем, но тогда будет возвращаться не `pd.DataFrame`, а `Dict[str, List[Union[float, GalacticStructureType]]]`. стоит?

2017-12-08 21:20 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    thick_disk_stars['galactic_structure_type'] = GalacticStructureType.thick
я понимаю твоё желание вынести всё, что можно из функции. но в данном случае какой-то сырой объект будем наружу выкидывать

2017-12-08 21:23 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +        uniform_rng: Callable[[float, float], float] = random.uniform
как скажешь..

2017-12-08 21:23 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +        uniform_rng: Callable[[float, float], float] = random.uniform
не понимаю, какой use-case может быть с другими генераторами

2017-12-09 01:42 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        uniform_rng: Callable[[float, float], float] = random.uniform
во-первых, в тестах мы можем подать тривиальный генератор, с которым получим более предсказуемое поведение и ограничения на результат будут жёстче

во-вторых, ничто не помешает пользователю передать в качестве параметра любую функцию с подходящей сигнатурой, но внутри неё может и не быть генерирования псевдорандомных чисел (как в нашем случае с тестами, будет казаться, что мы подаём неверную функцию и ожидаем корректное поведение -- звучит глупо, хотя на самом деле мы поступаем мудро)

в-третьих, абстрагироваться от деталей реализации всегда полезно, голова очищается

2017-12-09 01:44 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +        uniform_rng: Callable[[float, float], float] = random.uniform
в-четвёртых, предлагаю удалить эти функции так как у каждой из них один единственный пользователь и делать вызов на месте, а не делегировать одну инструкцию отдельной функции, в которой нет дополнительной логики

2017-12-09 02:48 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                                     / thick_disk_sfr_param))
что такое? почему не упростили
```python
    thick_disk_max_sfr_relative_time = thick_disk_sfr_param
    thick_disk_max_sfr = (thick_disk_max_sfr_relative_time
                          * math.exp(-thick_disk_max_sfr_relative_time
                                     / thick_disk_sfr_param))
```
до
```python
    thick_disk_max_sfr = thick_disk_max_sfr_relative_time * math.exp(-1)
```
?

2017-12-10 16:58 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    birth_initial_time = max_age - halo_age
аналогичная ситуация что и с `stars_count`?

2017-12-10 17:03 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    burst_times_mask = times >= burst_init_time
как насчёт `init` развернуть в полный вариант слова?

2017-12-10 17:03 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    while True:
вся проблема этой функции, что она может легко уйти в зацикливание

предлагаю сделать цикл `for` с некоторым заранее определённым максимальным количеством попыток (задаваемое параметром со значением по умолчанию, например), и если спустя данное количество попыток ничего не удалось сгенерировать -- кидать exception (типа `OverflowError`), а не висеть намертво

2017-12-10 17:03 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    while True:
аналогично

2017-12-10 17:05 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                              age: float,
это же возраст диска? возможно стоит указать добавив префикс

2017-12-10 17:05 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                             age: float,
аналогично

2017-12-10 21:10 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    birth_initial_time = max_age - halo_age
чувствую, ща ты меня попросишь вынести из `generate_thin_disk_stars`, и там такая каша будет..

2017-12-10 21:12 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    burst_times_mask = times >= burst_init_time
пропустил

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                   + birth_initial_time  # Shifting distribution
а где тут вызовы? разве сумма `partial` и `float` определена?

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
что за `time`?

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                               exponent: float) -> float:
можно сделать данный параметр keyword-only

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                          max_iterations_count: int = int(1e9)
что мешает написать `1000000000`? и зачем так много итераций? 1000 не хватит?

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                 rng: Callable[[], float] = random.random,
вроде договаривались это называть `generator`

2017-12-11 16:56 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                 rng_choice: Callable[[Iterable[Any]], Any] = random.choice
предлагаю в модуле объявить `random_sign = partial(random.choice, [-1, 1])`, а тут сделать параметр `sign_generator: Callable[[], int] = random_sign`

2017-12-11 17:11 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
могу и `x` назвать. есть предложения лучше? по сути это какое-то значение на оси абсцисс у функции плотности вероятности

2017-12-11 17:12 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
`x_pdf`?

2017-12-11 17:14 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
так что представляют из себя эти значения в нашем случае? какая величина? время? что именно за время?

2017-12-11 17:16 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                          max_iterations_count: int = int(1e9)
изначально стоял лимит на 6 миллионов звёзд - не белых карликов (т.е. не конечного набора).  initial mass function - имеет довольно маленькую площадь под графиком. итого, конечное число должно быть довольно большим. я проверял, с `1e9` он несколько секунд думает.
а насчет `1000000000`. тебе самому такая запись нравится?

2017-12-11 17:17 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                 rng: Callable[[], float] = random.random,
эту функцию не смотри, я её в другой модуль перекину. только не знаю, мержить и потом перекидывать, или сейчас её туда вставить. 
хотел после мержа. чё скажешь?

2017-12-11 17:18 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                          max_iterations_count: int = int(1e9)
тогда проще: `10**9`, будет `int`, можешь проверить

2017-12-11 17:18 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                 rng_choice: Callable[[Iterable[Any]], Any] = random.choice
эта функция в этом модуле не вызывается нигде

2017-12-11 17:19 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                 rng: Callable[[], float] = random.random,
перекинешь же, а не удалишь, я же предлагаю более абстрактные имена дать

2017-12-11 17:20 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                 rng_choice: Callable[[Iterable[Any]], Any] = random.choice
тогда как насчёт её удалить?

2017-12-11 17:21 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
нарисуй у себя в голове график функции плотности вероятности от нуля до `thick_disk_age`. вот по иксу и есть это время.

2017-12-11 17:22 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
сложно, я не хочу ничего рисовать в голове

2017-12-11 17:27 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +                 rng_choice: Callable[[Iterable[Any]], Any] = random.choice
удалил

2017-12-11 17:29 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +def thick_disk_star_birth_time(time: float,
любое время, короче. не знаю. то, чем является `x` для `y = f(x)`, тем является и `time` для `thick_disk_star_birth_time`

2017-12-12 04:42 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +    raise OverflowError('Exceeded maximum number of iterations '
можно по аналогии с [`progenitors_masses_births_times`](https://github.com/wolvespack/alcor/pull/17/files#diff-97d17e6b6797702a6b9437be50e5ad11R224) использовать `for`-`else`, так скорее всего будет читаемей вроде "если мы прошли цикл и дошли до конца без остановки, то значит произошла исключительная ситуация"

2017-12-12 04:42 UTC, lycantropos commented on alcor/services/simulations/sphere_stars.py
> +                        .format(function=function))
лучше использовать [`function.__qualname__`](https://www.python.org/dev/peps/pep-3155/), а то будет белиберда вроде
```python
>>> def foo():
...     pass
... 
>>> str(foo)
'<function foo at 0x7f925280ee18>'
```
в то время как
```python
>>> foo.__qualname__
'foo'
```

2017-12-12 04:42 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +            max_value=UNIVERSE_AGE - halo_birth_initial_time))
мб вынести
```python
    max_formation_time = UNIVERSE_AGE - halo_birth_initial_time
    return example(strategies.nonnegative_floats(max_value=max_formation_time))
```
?

2017-12-12 04:42 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +    return example(strategies.nonnegative_floats(max_value=UNIVERSE_AGE))
я бы `UNIVERSE_AGE` сделал фикстурой, можно `session`-scoped, если это константа
```python
@pytest.fixture(scope='session')
def universe_age() -> float:
    return UNIVERSE_AGE
```
это сделает фикстуры чище

2017-12-12 04:42 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +    return example(strategies.small_floats.filter(lambda x: x != 0))
для повышения читаемости предлагаю определить стратегию
```python
non_zero_small_floats = small_floats.filter(lambda x: x != 0)
```
можно сделать проще
```python
non_zero_small_floats = small_floats.filter(lambda x: x)
```
так как `0` – `False`-like значение

2017-12-12 04:42 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +                   .filter(lambda x: x != 0))
это же по сути уже `positive_floats`

2017-12-12 11:12 UTC, LostFan123 commented on alcor/services/simulations/sphere_stars.py
> +    raise OverflowError('Exceeded maximum number of iterations '
ок. но тогда почему мы опускаем `else` в случаях типа:
```python
if x > 0:
    return True
else:
    return False
```
?

2017-12-12 11:19 UTC, LostFan123 commented on tests/fixtures/sphere_stars.py
> +    return example(strategies.small_floats.filter(lambda x: x != 0))
выбираю первый вариант. так понятнее

2017-12-12 17:10 UTC, lycantropos commented on tests/strategies/sphere_stars.py
> +def nonnegative_floats_w_upper_limit(max_value: Optional[float] = None):
есть слово `finite`, а ещё так как это единственная стратегия для неотрицательных `float`'ов, то можно вовсе опустить постфикс `_w_upper_limit`

2017-12-12 17:19 UTC, lycantropos commented on tests/strategies/sphere_stars.py
> +                             allow_infinity=False).filter(lambda x: x != 0)
стоит для консистентности `0` -> `0.`

2017-12-12 17:38 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +@pytest.fixture(scope='function')
эта штука вряд ли поменяется, можно сделать `scope='session'`

2017-12-12 17:38 UTC, lycantropos commented on tests/fixtures/sphere_stars.py
> +                   exponent=initial_mass_function_parameter)
что мешает сделать
```python
    def function(x: float) -> float:
        return x ** initial_mass_function_parameter
    return function
```
? стоит почитать про замыкания (aka closure)

2017-12-12 17:49 UTC, lycantropos approved these changes

2017-12-12 18:16 UTC, merged