Removing decimals
lycantropos/alcor pull request #40
Opened 2017-10-12 17:34 UTC by lycantropos

Removed [`decimals.Decimal`](https://docs.python.org/3/library/decimal.html#decimal.Decimal) class support, moved to `float`.

2017-10-12 17:57 UTC, lycantropos commented on tests/strategies/stars.py
> +from functools import partial
надо с этим что-то делать, ща попробую поставить более старую версию

2017-10-12 18:12 UTC, GeorgySk requested changes

2017-10-12 18:12 UTC, LostFan123 commented on alcor/utils.py
> +                    Dict, Union)
новая строка

2017-10-12 18:12 UTC, LostFan123 commented on tests/models_tests/test_star.py
> +    assert max_coordinates_modulus >= min_cartesian_coordinates_modulus
по-хорошему надо было это другим коммитов добавлять

2017-10-12 18:12 UTC, LostFan123 commented on tests/strategies/stars.py
> +from functools import partial
импорт не на своем месте

2017-10-12 18:12 UTC, LostFan123 commented on tests/strategies/stars.py
> +    yield Star.proper_motion.name, positive_floats
аналогично. в другой коммит бы запихал, а не лепил бы в одну кучу

2017-10-12 18:14 UTC, LostFan123 commented on tests/strategies/stars.py
> +from functools import partial
не понял, про какую версию ты говоришь

2017-10-12 18:14 UTC, lycantropos commented on tests/models_tests/test_star.py
> +    assert max_coordinates_modulus >= min_cartesian_coordinates_modulus
это тесты на то, что никаких `Decimal` не образуется

2017-10-12 18:14 UTC, lycantropos commented on tests/strategies/stars.py
> +    yield Star.proper_motion.name, positive_floats
тоже часть тестов

2017-10-13 07:54 UTC, lycantropos commented on tests/strategies/stars.py
> +from functools import partial
это косяк PyCharm'а

2017-10-13 12:55 UTC, GeorgySk approved these changes

2017-10-13 15:13 UTC, merged