Tracks from hdf5
lycantropos/alcor pull request #42
Opened 2017-10-16 13:49 UTC by LostFan123

Instead of doing that trash in https://github.com/wolvespack/alcor/pull/25 (basically it was just repeating of what was going on in Fortran) I processed all the files, packed all processed data in hdf5 files and implemented reading from them.

2017-10-16 17:24 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +    return read_colors(path)
и что мешает объявить через `partial`?

2017-10-16 17:24 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                   file=file)
стоит закрывать файл после того как открыли, судя по [API](http://docs.h5py.org/en/latest/high/file.html#File.close) можно воспользоваться [`contextlib.closing`](https://docs.python.org/3/library/contextlib.html#contextlib.closing)
```python
from contextlib import closing
...
with closing(open_hdf5(path)) as file:
    one_tables = {}
    fill_one_table(one_tables,
                   file=file)
```

2017-10-16 17:24 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                   file=file)
к слову, зачем передавать пустой словарь внутрь? не легче ли будет его создавать внутри и возвращать заполненным?

2017-10-16 17:24 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                   file=file)
в других функциях аналогично

2017-10-19 04:12 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                              60: {}}
почему отличается от `da cooling`? в чём сакральный смысл именно этих `metallicities`?

2017-10-19 04:19 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +    return h5py.File(path,
вообще я имел ввиду использование [`contextlib.closing`](https://docs.python.org/3/library/contextlib.html#contextlib.closing) здесь, ещё можно эту функцию превратить в контекстный менеджер простым декорированием [`contextlib.contextmanager`](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager):
```python
from contextlib import (contextmanager, 
                        closing)
...
@contextmanager
def open_hdf5(path: str) -> h5py.File:
    base_dir = os.path.dirname(__file__)
    path = os.path.join(base_dir, path)
    with closing(h5py.File(path,
                           mode='r')) as file:
        yield file
```
потом использовать по аналогии с [`open`](https://docs.python.org/3/library/functions.html#open):
```python
with open_hdf5(path) as file:
    ...do stuff...
```

2017-10-19 04:23 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +    return list(map(str, indexes))
можно сделать короче используя [`map`](https://docs.python.org/3/library/functions.html#map) & [`sorted`](https://docs.python.org/3/library/functions.html#sorted):
```python
integer_indexes = sorted(map(int, indexes))
return list(map(str, integer_indexes))
```

2017-10-19 04:28 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +                             60: range(111, 120)}
это и всё остальное должно быть оформлено в качестве [фикстуры](https://docs.pytest.org/en/latest/fixture.html)

2017-10-19 04:28 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +            base_dir=base_dir)
в этом test-case происходит слишком много неочевидного и проверяются только итоговые результаты, значит все промежуточные должны быть протестированы отдельно, а здесь переданы в качестве фикстур

2017-10-19 04:28 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +def tracks_lengths(sequences: Dict[int, pd.DataFrame]) -> List[int]:
это тоже должно быть фикстурой

2017-10-19 04:28 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +                                     './fort_files/fort.' + str(fort_link))
это стоит делать в каком-нибудь `list comprehension`, а в цикле уже работать с «нормальными» путями

2017-10-19 04:28 UTC, lycantropos commented on requirements.txt
> +h5py
мы это обсуждали, это должно быть в `setup.py`, в `requirements.txt` зависимости самого `manage.py`

2017-10-19 15:17 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                                              60: {}}
уфф.. если бы я знал

2017-10-22 16:56 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +    return h5py.File(path,
done

2017-10-22 21:09 UTC, LostFan123 commented on fortran_tests/tables/test_tracks.py
> +            base_dir=base_dir)
какие тесты для промежуточных результатов предлагаешь?

2017-10-23 11:13 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                              60: {}}
может вынесем эти `1, 10, 30, 60` в качестве параметра со значением по умолчанию, а само значение сделаем `tuple`? а тут будет
```python
da_cooling_tracks_by_metallicities = {metallicity: {} 
                                      for metallicity in metallicities}
```

2017-10-23 11:13 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                    dict(cooling_time=file[mass_group + 'cooling_time'],
предлагаю использовать `os.path.join` вместо явного использования  `/` (или `posixpath.join` если этот путь всегда со `/`)

2017-10-23 11:13 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +            cooling_tracks=cooling_tracks_by_metallicities)
для фикстур есть специальная одноимённая директория, следует поместить в модуль типа `tracks.py`, тут импортировать их конечно же не нужно будет

2017-10-23 11:13 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +                one_fort_files_lengths) -> None:
тайпинги

2017-10-23 11:13 UTC, lycantropos commented on fortran_tests/tables/test_tracks.py
> +def tracks_lengths(sequences: Dict[int, pd.DataFrame]) -> List[int]:
всё ещё не фикстура как и функции ниже

2017-10-23 11:30 UTC, lycantropos commented
почему тесты находятся в директории `fortran_tests`? стоит поместить в директорию `tests`

2017-10-23 11:31 UTC, lycantropos commented
почему тесты находятся в директории `fortran_tests`? стоит поместить в директорию `tests`

2017-10-23 15:16 UTC, lycantropos commented on .gitignore
> -fort.*
в чём дело? почему не игнорируем?

2017-10-23 15:16 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                file: h5py.File) -> Dict[int, pd.DataFrame]:
незачем keyword-only при единственном параметре

2017-10-23 15:16 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                   file: h5py.File) -> Dict[int, pd.DataFrame]:
аналогично

2017-10-23 15:20 UTC, LostFan123 commented on .gitignore
> -fort.*
я сказал: тесты не проходят без этих файлов

2017-10-23 15:28 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                file: h5py.File) -> Dict[int, pd.DataFrame]:
done

2017-10-23 19:11 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
это неправда, если вне докера, то ничего не выйдет, а если поменяем путь в докере, тоже всё поломается

2017-10-23 19:13 UTC, lycantropos commented on tests/fixtures/tables.py
> +                                        base_dir: str) -> List[int]:
это не так делается, никаких keyword-only, фикстуры `fort_links` & `base_dir` нет и в помине

2017-10-24 18:17 UTC, LostFan123 commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
`os.path.relpath('../tables')` почему-то не хочет работать

2017-10-24 18:20 UTC, LostFan123 commented on tests/fixtures/tables.py
> +                                        base_dir: str) -> List[int]:
??? и чё мне с этой функцией делать тогда?

2017-10-26 02:17 UTC, lycantropos commented on tests/tables/fort_files/fort.101
> +0.778605	4.808539	0.000994579	7.560106
и что мешает весь этот мусор запихать в архив и разархивировать перед запуском тестов?

2017-10-26 02:17 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
мб потому что надо использовать [`os.path.abspath`](https://docs.python.org/3/library/os.path.html#os.path.abspath), а не относительный путь превращать в относительный путь

2017-10-26 02:17 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
ещё можно запустить дебаггер, и с помощью [Evaluate expression](https://www.jetbrains.com/help/pycharm/evaluating-expressions.html) и документации модуля [`os.path`](https://docs.python.org/3/library/os.path.html) вычислить необходимый путь

2017-10-26 02:17 UTC, lycantropos commented on tests/fixtures/tables.py
> +                                        base_dir: str) -> List[int]:
я ступил, её не нужно делать фикстурой, вытащи как утилиту в *tests/utils.py* например

2017-10-26 02:17 UTC, lycantropos commented on tests/fixtures/tables.py
> +def fort_files_lengths(fort_links: Iterator,
тут аналогично фикстура не нужна

2017-10-26 18:42 UTC, LostFan123 commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
`os.path.abspath('../tables')` тоже не работает:

> No such file or directory: '/tables/fort_files/fort.11'

я пока без дебагера. можешь глянуть сам?

2017-10-27 02:05 UTC, lycantropos requested changes

2017-10-27 02:05 UTC, lycantropos commented on docker-compose.debug.yml
> +    entrypoint: "/alcor/docker-entrypoint.debug.sh"
скорее всего можно без кавычек, но это дело вкуса

2017-10-27 02:05 UTC, lycantropos commented on docker-entrypoint.debug.sh
> +#!/usr/bin/env bash
мб не **...debug...**, а **...test...**?

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
зачем брать абсолютный путь от абсолютного пути? стоит почитать документацию и затем потыкать в консоли, вставить сюда
```python
print(os.getcwd())
```
чтобы узнать текущую рабочую директорию во время прогонки тестов и относительно неё определить путь до **/alcor/tests/tables**.

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +            base_dir=FORT_FILES_PATH)
кода будет меньше, если сделать `partial` со вшитым `base_dir`

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +def tracks_lengths(sequences: Dict[int, pd.DataFrame]) -> List[int]:
эта функция не используется в других функциях в качестве параметра, т.е. не является фикстурой, стоит вынести в утилиты в качестве обычной функции

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +def tracks_lengths(sequences: Dict[int, pd.DataFrame]) -> List[int]:
тем более фикстуры `sequences` нет и это вообще некорректный код

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +def tracks_lengths(sequences: Dict[int, pd.DataFrame]) -> List[int]:
стоит почитать документацию `pytest`

2017-10-27 02:05 UTC, lycantropos commented on tests/fixtures/tables.py
> +    return tracks_lengths(sequences=characteristics)
зачем передавать keyword-ом то, что находится в единственном числе? по-моему, это имеет смысл если параметров больше чем один

2017-10-27 02:05 UTC, lycantropos commented on tests/tables/fort_files/fort.101
> +0.778605	4.808539	0.000994579	7.560106
эти файлы всё ещё в репозитории и не удалены

2017-10-27 07:50 UTC, lycantropos commented on tests/fixtures/tables.py
> +@pytest.fixture
стоит указывать `scope`, это не займёт много времени, зато избавит от неконсистентности в случае когда `scope` не равен `'function'`

2017-10-27 08:39 UTC, lycantropos commented on tests/fixtures/tables.py
> +    for mass, sequence in sorted(sequences.items()):
нам правда нужна сортировка по массе?

2017-10-27 08:39 UTC, lycantropos commented on tests/fixtures/tables.py
> +    for mass, sequence in sorted(sequences.items()):
не забывай, что неиспользуемые объекты лучше заменять на `_`

2017-10-27 09:18 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
если это пути, то нужно их передавать и объявлять через `os.path.join`, а не сырой строкой разделённой через слеш

2017-10-27 09:18 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +            cooling_tracks_by_metallicity = cooling_tracks[metallicity]
не зависит от `mass`, можно вынести за пределы цикла

2017-10-27 10:08 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                color_j=file[join_group(mass_group, 'color_j')]))
такие вещи проще делать через генератор `tuple`'ов `key, value`, а потом через превращение в словарь пользователем:
```python
def foo(elements: Iterable[Hashable]) -> Iterator[Tuple[Hashable, Any]]:
    for element in elements:
        yield element, bar(element)
```
где `foo` в нашем случае `fill_one_table`, а `bar` – `pd.DataFrame(dict(...))`

а в месте использования просто
```python
foo_dict = dict(foo(elements))
```

2017-10-27 10:10 UTC, lycantropos commented on tests/utils.py
> +    for _, sequence in sorted(sequences.items()):
тут правда нужна сортировка по ключам?

2017-10-27 10:27 UTC, lycantropos commented on tests/utils.py
> +                                   'fort_files/fort.' + str(fort_link))
это так не делается
- стоит передавать путь до директории **fort_files**, а не `base_dir`
- `'fort.'` можно захардкодить, но можно написать функцию, которая из `fort_link` (типа `int`) получает `fort_file_name` (типа `str`) вроде
```python
def fort_file_name(file_index: int) -> str:
    return 'fort.' + str(file_index)
```
тогда тут останется простой `map`
- `fort_link` – некорректное имя, оно никуда не ссылается, это скорее индекс, соответственно все связанные объекты вводят в заблуждение

2017-10-27 14:28 UTC, LostFan123 commented on docker-compose.debug.yml
> +    entrypoint: "/alcor/docker-entrypoint.debug.sh"
по твоему примеру вроде как

2017-10-27 14:28 UTC, LostFan123 commented on docker-entrypoint.debug.sh
> +#!/usr/bin/env bash
по аналогии с docker-compose файлом. ну ладно, переименую в test

2017-10-27 14:29 UTC, LostFan123 commented on docker-entrypoint.debug.sh
> +#!/usr/bin/env bash
а, ты уже..

2017-10-27 14:35 UTC, LostFan123 commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('/alcor/tests/tables')
`'tests/tables'` всё-таки. хм, ну ок. странно

2017-10-27 14:42 UTC, LostFan123 commented on tests/fixtures/tables.py
> +    for mass, sequence in sorted(sequences.items()):
да, без сортировки всё ломается на 3.5

2017-10-27 14:43 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
ок, но в сигнатуре, наверное, лучше этого не делать?

2017-10-27 14:54 UTC, LostFan123 commented on tests/utils.py
> +    for _, sequence in sorted(sequences.items()):
если я ничего не путаю, то тут на 3.5 Travis ломался

2017-10-27 15:06 UTC, LostFan123 commented on tests/utils.py
> +                                   'fort_files/fort.' + str(fort_link))
http://docs.cray.com/books/S-3695-35/html-S-3695-35/pdollsmg.html
есть идеи получше как назвать эти 'индексы'?

2017-10-27 15:54 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
лучше вообще по возможности избегать значений по умолчанию на нижнем уровне, как мне кажется, это вводит пользователей в заблуждение, потому что внизу в кишках происходит то, на что он повлиять не в силах не переписав всё самому

2017-10-27 16:10 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
короче, когда будем подрубать этот модуль. то сверху подадим этот путь. а пока пусть так будет, чтоб тесты проходили. ок?

2017-10-27 21:26 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
без проблем

2017-10-27 21:31 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('tests/tables')
тут я ещё ступил, надо `os.join` заюзать, чтобы выглядело ок

2017-10-27 21:31 UTC, lycantropos commented on tests/fixtures/tables.py
> +FORT_FILES_PATH = os.path.abspath('tests/tables')
и судя по всему тут отсутствует `fort_files`?

2017-10-28 20:49 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                                           'luminosity')]))
мб мы это нормально генерализуем вроде
```python
tracks = OrderedDict((key, file[join_group(mass_group,
                                           key)])
                     for key in ['cooling_time',
                                 'effective_temperature',
                                 'luminosity'])
cooling_tracks_by_metallicity[int(mass)] = pd.DataFrame(tracks)
```

2017-10-28 20:49 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                color_j=file[join_group(mass_group, 'color_j')]))
тут и ниже аналогично

2017-10-29 16:15 UTC, lycantropos commented on docker-compose.debug.yml
> +    entrypoint: "/alcor/docker-entrypoint.tests.sh"
неконсистентно, снизу кавычек нет

2017-10-29 16:15 UTC, lycantropos commented on tests/utils.py
> +    for _, sequence in sequences.items():
можно просто итерироваться по `dict.values`

2017-10-29 16:15 UTC, lycantropos commented on tests/utils.py
> +        yield from tracks_lengths(sequences=sequences)
незачем передавать keyword'ом единственный аргумент

2017-10-29 16:15 UTC, lycantropos commented on tests/utils.py
> +    for fort_links_range in fort_links.values():
тогда логичнее исходный объект назвать `fort_links_ranges`

2017-10-29 16:15 UTC, lycantropos commented on tests/utils.py
> +    for fort_links_range in fort_links.values():
и что такое `fort` было бы неплохо уточнить

2017-10-30 12:15 UTC, LostFan123 commented on docker-compose.debug.yml
> +    entrypoint: "/alcor/docker-entrypoint.tests.sh"
как скажешь

2017-10-30 12:16 UTC, LostFan123 commented on tests/utils.py
> +    for _, sequence in sequences.items():
глаз-алмаз

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                 metallicities: Tuple[int]
это `Tuple` из одного значения? вряд ли, скорее всего там их неопределённое количество, поэтому `Tuple[int, ...]`

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +        return OrderedDict(fill_colors(file=file))
можно не передавать как keyword аргумент в функции с одним параметром

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def read_one_tables(path: str = 'input_data/one_wds_tracks.hdf5'
не вижу разницы между `read_colors`, `read_one_tables`, только `fill_*` различается, вообще имеет смысл это в отдельные функции выносить? мб тогда одну нафигачить и эти `fill_*` параметром передавать, а потом сделать `partial`'ы, если это конечно не over-engineering

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +        masses = sort_mass_indexes(indexes=file[metallicity_group])
стоит ли как-то в названии указать, что `mass` является строкой? типа `masses_strings`

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                             'luminosity'])
эта вещь захардкожена, что мешает вынести хотя бы как параметр со значением по умолчанию (а лучше сверху как-то его передавать)?

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                         'color_j'])
аналогичный вопрос

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                         'color_j'])
вроде бы где-то в тестах подобный список уже фигурировал

2017-12-03 16:27 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                                         'color_j'])
те же, что и в `fill_colors` + `['effective_temperature']`, в остальном же функция идентична, стоит подумать над DRY

2017-12-03 17:08 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                                             'luminosity'])
ага, так и сделаю ща. заодно проблема с `read_colors` и `read_one_tables` должна решиться

2017-12-03 17:14 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                                         'color_j'])
насчет подобных списков. после мержа надо будет глянуть, там в обоих PR такие они были

2017-12-03 18:18 UTC, lycantropos commented on .travis.yml
> -  - "3.6"
ну как ты так ребейз-то делаешь? меня это поражает просто, проверяй прежде чем пушить

2017-12-03 18:19 UTC, LostFan123 commented on .travis.yml
> -  - "3.6"
что за бреееееееееееееед

2017-12-03 18:20 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def fill_colors_or_one_table(*,
почему не просто `fill_interest_parameters`?

2017-12-03 18:31 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                             for parameter in interest_parameters)
зачем `OrderedDict` по `Set`, ведь последний не упорядочен?

2017-12-03 18:41 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +def fill_colors_or_one_table(*,
потому что тут правильно говорить: "мы заполняем таблицу данными", а не "мы заполняем данные"

2017-12-04 02:10 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +def fill_colors_or_one_table(*,
тогда `fill_table`?

2017-12-05 17:10 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +        for mass in masses_strings:
`mass_string` тогда же?

2017-12-05 17:17 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                          metallicities=(1, 10, 60))
я так понимаю, не имеет пока смысла узнавать, почему именно эти значения?

2017-12-05 17:25 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                          metallicities=(1, 10, 60))
всё, что я знаю, это то, что 0.001 - subsolar metallicity, 0.01 - solar metallicity, 0.03 и 0.06 - supersolar metallicity

2017-12-05 17:25 UTC, LostFan123 commented on alcor/services/simulations/tracks.py
> +                          metallicities=(1, 10, 60))
почему именно такие, узнаю как-нибудь

2017-12-05 17:39 UTC, lycantropos commented on alcor/services/simulations/tracks.py
> +                          interest_parameters=DA_DB_INTEREST_PARAMETERS)
почему `metallicities` передаётся как `tuple`, а `interest_parameters` -- как `list`?

2017-12-05 18:05 UTC, lycantropos commented on tests/utils.py
> +                                        base_dir: str) -> List[int]:
почему бы не перенести `FORT_FILES_PATH` сюда и поставить в качестве значения по умолчанию?

2017-12-05 18:05 UTC, lycantropos commented on tests/utils.py
> +                       fort_files_dir: str) -> List[int]:
аналогично, тогда и тот `partial` можно будет убрать

2017-12-05 18:06 UTC, lycantropos approved these changes

2017-12-06 11:26 UTC, LostFan123 commented on tests/utils.py
> +                                        base_dir: str) -> List[int]:
эта константа ещё и в другую функцию подаётся: `fort_files_lengths`

2017-12-06 11:27 UTC, LostFan123 commented on tests/utils.py
> +                       fort_files_dir: str) -> List[int]:
т.е. это нормально одни и те же значения в сигнатуру двух разных функций, как значения по умолчанию поставить?

2017-12-06 13:46 UTC, merged